version: "3"

services:
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  src:
    build: .
    working_dir: /app
    volumes:
      - ./src:/app
    ports:
      - "5000:8080"
    depends_on:
      - db
